# Generated by Django 3.1.2 on 2022-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('mohallah_no', models.CharField(default='', max_length=50)),
                ('street_no', models.CharField(default='', max_length=50)),
                ('house_no', models.CharField(default='', max_length=50)),
                ('rooms', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
