# Generated by Django 3.1.2 on 2022-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.CharField(default='', max_length=50)),
                ('height', models.CharField(default='', max_length=50)),
                ('weight', models.CharField(default='', max_length=50)),
                ('colour', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
