# Generated by Django 3.1.2 on 2022-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('numbers', models.CharField(default='', max_length=50)),
                ('characteristics', models.CharField(default='', max_length=50)),
                ('materials', models.CharField(default='', max_length=50)),
                ('moter', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
